server:
  port: 8040

spring:
  kafka:
    properties:
      otel:
        propagation: b3
    consumer:
      paymentTopicName: payment-topic
      paymentGroupId: paymentGroup
      orderTopicName: order-topic
      orderGroupId: orderGroup
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      offSetReset: earliest
      keyDeSerializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeSerializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schemaRegistryUrl: "http://127.0.0.1:8081"
      timeZone: UTC
    dlq:
      paymentDlqtopicName: payment-notifications-dlq
      orderDlqtopicName: order-notifications-dlq
      groupId: notification-dlq
      partitions: 10
      replicas: 3
      maxAttempts: 3
      backOffInterval: 2000
      multiplier: 2.0
      maxInterval: 15000
      concurrency: 3
      ack: MANUAL
      missingTopicsFatal: false
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

invoice:
  downloadUrl: http://localhost:8222/api/v1
  senderEmailAddress: noreply@forsaken-ecommerce.com
  jasperTemplatePath: reports/invoice_template.jrxml
  companyLogoPath: reports/accenture-logo.png
  userLogoPath: reports/icon-user.png
  emailLogoPath: reports/icon-email.png
  amountLogoPath: reports/icon-amount.png
  paymentLogoPath: reports/icon-payment.png
  calendarLogoPath: reports/icon-calendar.png

aws:
  secretsmanager:
    secretName: EcommerceCredentials
  s3:
    bucketName: my-invoice-pdfs-prod
    expiration: 30
  dynamodb:
    tableName: Notification