server:
  port: 8040

spring:
  kafka:
    properties:
      otel:
        propagation: b3
    consumer:
      paymentTopicName: payment-topic
      paymentGroupId: paymentGroup
      orderTopicName: order-topic
      orderGroupId: orderGroup
      maxPollIntervalMs: 900000
      maxPollRecords: 1
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      offSetReset: earliest
      keyDeSerializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeSerializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schemaRegistryUrl: "http://127.0.0.1:8081"
      timeZone: UTC
    dlq:
      paymentDlqTopicName: payment-notifications-dlq
      orderDlqTopicName: order-notifications-dlq
      groupId: notification-dlq
      partitions: 10
      replicas: 3
      maxRetries: 3
      backOffInterval: 2000
      multiplier: 2.0
      maxInterval: 15000
      concurrency: 3
      ack: MANUAL
      missingTopicsFatal: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

invoice:
  downloadUrl: http://localhost:8222/api/v1
  senderEmailAddress: noreply@forsaken-ecommerce.com
  jasperTemplatePath: reports/invoice_template.jrxml
  companyLogoPath: /reports/accenture-logo.png
  userLogoPath: /reports/icon-user.png
  emailLogoPath: /reports/icon-email.png
  amountLogoPath: /reports/icon-amount.png
  paymentLogoPath: /reports/icon-payment.png
  calendarLogoPath: /reports/icon-calendar.png

aws:
  secretsmanager:
    secretName: EcommerceCredentials
  s3:
    bucketName: my-invoice-pdfs-prod
    expiration: 120  # Pre-signed URL expiration (in minutes).
    dlq:
      bucket: dlq-bucket-prod
      paymentPrefix: payment-dlq
      orderPrefix: order-dlq
  dynamodb:
    tableName: Notification