package com.forsaken.ecommerce.order.payment;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

/**
 * Feign client for communicating with the Payment Service.
 * <p>
 * This client is responsible for initiating payment requests for orders.
 * The base URL of the Payment Service is configured through the property
 * {@code application.config.payment-url}. Implementations are generated
 * automatically by Spring Cloud OpenFeign.
 * </p>
 *
 * <p><b>Usage Example:</b></p>
 * <pre>
 * Integer paymentId = paymentClient.requestOrderPayment(
 *         new PaymentRequest(orderId, amount, method)
 * );
 * </pre>
 *
 * <p><b>Error Handling:</b></p>
 * <ul>
 *     <li>Feign throws {@code FeignException} for non-2xx responses,
 *         such as validation errors, insufficient balance, or service failure.</li>
 *     <li>Network issues or timeouts also result in Feign runtime exceptions.</li>
 * </ul>
 *
 * @see PaymentRequest
 */
@FeignClient(
        name = "payment-service",
        url = "${application.config.payment-url}"
)
public interface IPaymentClient {

    /**
     * Sends a payment initiation request to the Payment Service.
     * <p>
     * The request contains the necessary payment information required to
     * authorize and process payment for a specific order. The Payment Service
     * validates the request, performs business checks, and returns a unique
     * identifier representing the created payment transaction.
     * </p>
     *
     * @param request the payment request payload containing order ID, amount,
     *                payment details, and metadata; must not be null
     * @return the unique identifier of the payment transaction generated by the Payment Service
     * @throws feign.FeignException if the Payment Service responds with an error status
     *                              (e.g., validation failure, insufficient funds, server error)
     */
    @PostMapping
    Integer requestOrderPayment(@RequestBody final PaymentRequest request);
}
