server:
  port: 8070

application:
  config:
    payment:
      url: http://localhost:8222/api/v1/payments
      connect-timeout: 2s
      read-timeout: 5s
    customer:
      url: http://localhost:8222/api/v1/customers
      connect-timeout: 2s
      read-timeout: 5s
    product:
      url: http://localhost:8222/api/v1/products
      connect-timeout: 2s
      read-timeout: 5s

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      topicName: order-topic
      partitions: 10
      replicationFactor: 3
      minInSyncReplicas: 2
      ack: all
      retries: 5
      compressionType: gzip
      retryBackOffMs: 200
      isUncleanElection: false
      maxPollIntervalMs: 900000
      maxPollRecords: 1
      bootstrapServers: localhost:9092,localhost:9093,localhost:9094
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schemaRegistryUrl: "http://127.0.0.1:8081"
  cloud:
    openfeign:
      client:
        config:
          payment-service:
            url: ${application.config.payment.url}
          customer-service:
            url: ${application.config.customer.url}

aws:
  secretsmanager:
    dbSecretName: OrderServiceSecrets

general:
  configurations:
    maxPageSize: 50
    defaultPageSize: 5
    defaultPageNumber: 0