server:
  port: 8050

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    repair-on-migrate: true
    enabled: false
    baseline-description: "init"
    baseline-version: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  secretsmanager:
    accessSecretName: EcommerceCredentials
    dbSecretName: ProductServiceSecrets
  s3:
    bucketName: my-product-images-47
    expiration: 30