server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/ecommerce

general:
  configurations:
    maxPageSize: 50
    defaultPageSize: 5
    defaultPageNumber: 0