server:
  port: 8090

spring:
  redis:
    host: redis
    port: 6379

  cache:
    type: redis

app:
  cache:
    ttlMinutes: 15

aws:
  secretsmanager:
    secretName: EcommerceCredentials
  dynamodb:
    tableName: Customers

general:
  configurations:
    maxPageSize: 50
    defaultPageSize: 5
    defaultPageNumber: 1