package com.forsaken.ecommerce.notification.service;


import java.net.URL;

/**
 * Contract for interacting with object storage to manage invoice documents.
 * <p>
 * Implementations of this interface are responsible for:
 * <ul>
 *     <li>Uploading generated invoice PDFs to object storage (e.g. Amazon S3)</li>
 *     <li>Returning a stable storage key for later retrieval</li>
 *     <li>Generating time-limited pre-signed URLs for secure, temporary access</li>
 * </ul>
 * </p>
 *
 * <p>
 * This interface abstracts the underlying storage provider and access mechanism.
 * Consumers of this service should rely only on the contract defined here and
 * remain unaware of vendor-specific APIs or authentication details.
 * </p>
 *
 * <p><b>Security:</b><br>
 * Pre-signed URLs generated by implementations are expected to be
 * short-lived and suitable for public access without exposing
 * permanent credentials.
 * </p>
 *
 * <p><b>Thread Safety:</b><br>
 * Implementations should be stateless and safe for concurrent use, as they are
 * typically managed as singleton beans in a Spring application.
 * </p>
 */
public interface IS3Service {

    /**
     * Uploads a PDF invoice to object storage and returns the generated storage key.
     *
     * <p>
     * The provided byte array is expected to represent a valid PDF document.
     * The returned key uniquely identifies the stored object and can be used
     * later to generate a pre-signed access URL.
     * </p>
     *
     * @param pdfBytes  the raw PDF content to be uploaded
     * @param invoiceId the unique identifier of the invoice, used to derive
     *                  the storage object key
     * @return the storage key of the uploaded invoice (e.g. {@code invoices/{invoiceId}.pdf})
     * @throws IllegalArgumentException if {@code pdfBytes} is {@code null} or empty, or if {@code invoiceId}
     *                                  is {@code null} or blank
     */
    String uploadInvoice(
            final byte[] pdfBytes,
            final String invoiceId
    ) throws IllegalArgumentException;

    /**
     * Generates a time-limited pre-signed URL for accessing an invoice.
     *
     * <p>
     * The returned URL allows temporary, secure read access to the stored
     * invoice without requiring authentication credentials.
     * </p>
     *
     * @param key the storage key of the invoice object
     * @return a pre-signed {@link URL} that can be used to download the invoice
     * @throws IllegalArgumentException if {@code key} is {@code null} or blank
     */
    URL generatePresignedUrl(final String key) throws IllegalArgumentException;
}
